# Generated by Django 3.2.4 on 2021-06-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCertificate',
            fields=[
                ('id_certificate', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=256)),
                ('certificate_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_phone_number', models.CharField(max_length=20)),
                ('client_message', models.TextField()),
                ('status', models.CharField(default='Новая заявка', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_category', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('certificate_number', models.CharField(max_length=7)),
                ('status', models.CharField(default='выпущен', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Payed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('sum', models.IntegerField()),
                ('status', models.CharField(default='not paid', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
    ]
