# Generated by Django 3.2.4 on 2021-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_message',
            field=models.TextField(null=True),
        ),
    ]
