# Generated by Django 3.2.4 on 2021-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0002_alter_application_client_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
