# Generated by Django 3.2.4 on 2021-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0004_alter_application_client_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecertificate',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
