# Generated by Django 3.2.4 on 2021-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0005_activecertificate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='id_certificate',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
