# Generated by Django 3.2.4 on 2021-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0007_reviews_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='id',
        ),
        migrations.AddField(
            model_name='reviews',
            name='id_review',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
