# Generated by Django 3.2.4 on 2021-06-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0009_auto_20210626_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id_worker', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=40)),
                ('worker_img', models.ImageField(upload_to='')),
                ('worker_desc', models.TextField()),
            ],
        ),
    ]
