# Generated by Django 3.2.4 on 2021-06-29 02:49

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0011_alter_workers_worker_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='worker_img',
            field=models.ImageField(upload_to=[pathlib.PureWindowsPath('D:/webdev/DJANGO/AMMA/AMMA_PROJECT/media')]),
        ),
    ]
