# Generated by Django 3.2.4 on 2021-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0013_alter_workers_worker_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massages',
            fields=[
                ('id_serv', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id_serv', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spafortwo',
            fields=[
                ('id_serv', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
            ],
        ),
    ]
