# Generated by Django 3.2.4 on 2021-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0014_massages_spa_spafortwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayClient',
            fields=[
                ('id_client', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('client_email', models.CharField(max_length=200)),
            ],
        ),
    ]
