# Generated by Django 3.2.4 on 2021-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0015_payclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payed',
            name='id',
        ),
        migrations.AddField(
            model_name='payed',
            name='id_payed',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
