# Generated by Django 3.2.4 on 2021-07-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0018_rename_use_statue_payed_use_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='massages',
            name='price4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massages',
            name='time1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massages',
            name='time2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massages',
            name='time3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massages',
            name='time4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
