# Generated by Django 3.2.4 on 2021-07-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0019_auto_20210707_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='payed',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
