# Generated by Django 3.2.4 on 2021-07-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0023_activeaboniment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeaboniment',
            old_name='aboniment_image',
            new_name='certificate_image',
        ),
    ]
