# Generated by Django 3.2.4 on 2021-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0025_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamam',
            fields=[
                ('id_hamam', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('price_1', models.IntegerField()),
                ('time_1', models.IntegerField()),
                ('price_2', models.IntegerField()),
                ('time_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hidromassage',
            fields=[
                ('id_hidromassage', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('price_1', models.IntegerField()),
                ('time_1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id_salt', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('desc_price_1', models.CharField(max_length=100)),
                ('price_1_1', models.IntegerField()),
                ('price_1_2', models.IntegerField()),
                ('desc_price_2', models.CharField(max_length=100)),
                ('price_2_1', models.IntegerField()),
                ('price_2_2', models.IntegerField()),
                ('desc_price_3', models.CharField(max_length=100)),
                ('price_3_1', models.IntegerField()),
                ('price_3_2', models.IntegerField()),
                ('desc_price_4', models.CharField(max_length=100)),
                ('price_4_1', models.IntegerField()),
                ('price_4_2', models.IntegerField()),
            ],
        ),
    ]
