# Generated by Django 3.2.4 on 2021-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0026_hamam_hidromassage_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt',
            name='time_13_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salt',
            name='time_1_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salt',
            name='time_1_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salt',
            name='time_2_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salt',
            name='time_2_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salt',
            name='time_3_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
