# Generated by Django 3.2.4 on 2021-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amma', '0027_auto_20210709_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salt',
            old_name='time_13_2',
            new_name='time_3_2',
        ),
        migrations.AddField(
            model_name='salt',
            name='time_4_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salt',
            name='time_4_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
